# Generated by Django 4.2.4 on 2023-11-10 04:32

from django.db import migrations, models
import django.db.models.deletion
import isucon.portal.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0010_team_want_local_participation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='タイトル')),
                ('description', models.TextField(verbose_name='本文')),
                ('is_enabled', models.BooleanField(blank=True, verbose_name='表示')),
            ],
            options={
                'verbose_name': 'お知らせ',
                'verbose_name_plural': 'お知らせ',
            },
            bases=(isucon.portal.models.LogicalDeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=100, verbose_name='ホスト名')),
                ('global_ip', models.CharField(max_length=100, unique=True, verbose_name='グローバルIPアドレス')),
                ('private_ip', models.CharField(max_length=100, verbose_name='プライベートIPアドレス')),
                ('is_bench_target', models.BooleanField(default=False, verbose_name='ベンチマークターゲットであるかのフラグ')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='servers', to='authentication.team', verbose_name='チーム')),
            ],
            options={
                'verbose_name': 'サーバ',
                'verbose_name_plural': 'サーバ',
                'unique_together': {('team', 'hostname')},
            },
            bases=(isucon.portal.models.LogicalDeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('best_score', models.IntegerField(default=0, verbose_name='ベストスコア')),
                ('best_scored_at', models.DateTimeField(blank=True, null=True, verbose_name='ベストスコア日時')),
                ('latest_score', models.IntegerField(default=0, verbose_name='最新スコア')),
                ('latest_scored_at', models.DateTimeField(blank=True, null=True, verbose_name='最新スコア日時')),
                ('latest_is_passed', models.BooleanField(blank=True, default=False, verbose_name='最新のベンチマーク成否フラグ')),
                ('team', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='authentication.team')),
            ],
            options={
                'verbose_name': 'チームスコア',
                'verbose_name_plural': 'チームスコア',
                'ordering': ('-latest_score', '-best_score', 'best_scored_at', 'team'),
            },
            bases=(isucon.portal.models.LogicalDeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_ip', models.CharField(blank=True, max_length=100, verbose_name='対象サーバIPアドレス')),
                ('status', models.CharField(choices=[('waiting', 'waiting'), ('running', 'running'), ('done', 'done'), ('aborted', 'aborted'), ('canceled', 'canceled')], default='waiting', max_length=100, verbose_name='進捗')),
                ('is_passed', models.BooleanField(default=False, verbose_name='正答フラグ')),
                ('reason', models.TextField(blank=True, verbose_name='結果メッセージ')),
                ('score', models.IntegerField(default=0, verbose_name='獲得スコア')),
                ('stdout', models.TextField(blank=True, verbose_name='ログ標準出力')),
                ('stderr', models.TextField(blank=True, verbose_name='ログ標準エラー出力')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最終更新日時')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='確定時刻')),
                ('target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contest.server', verbose_name='対象サーバ')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.team', verbose_name='チーム')),
            ],
            options={
                'verbose_name': 'ジョブ',
                'verbose_name_plural': 'ジョブ',
                'ordering': ('-created_at',),
            },
        ),
    ]
