# Generated by Django 4.2.4 on 2023-11-21 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, verbose_name='有効かどうか'),
        ),
        migrations.AddField(
            model_name='job',
            name='is_test',
            field=models.BooleanField(blank=True, default=False, verbose_name='テストかどうか'),
        ),
        migrations.AddField(
            model_name='score',
            name='test_is_passed',
            field=models.BooleanField(blank=True, default=False, verbose_name='テストベンチマーク成否フラグ'),
        ),
        migrations.AddField(
            model_name='score',
            name='test_score',
            field=models.IntegerField(blank=True, null=True, verbose_name='テストスコア'),
        ),
        migrations.AddField(
            model_name='score',
            name='test_scored_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='テストスコア日時'),
        ),
        migrations.AlterField(
            model_name='job',
            name='is_passed',
            field=models.BooleanField(blank=True, default=False, verbose_name='正答フラグ'),
        ),
    ]
