# Generated by Django 4.2.4 on 2023-11-23 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0002_job_is_active_job_is_test_score_test_is_passed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='is_checked',
            field=models.BooleanField(blank=True, default=True, verbose_name='チェック済み'),
        ),
    ]
