# Generated by Django 4.2.4 on 2023-11-23 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0003_server_is_checked'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='resolved_count',
            field=models.IntegerField(default=0, verbose_name='名前解決成功数'),
        ),
    ]
