# Generated by Django 4.2.4 on 2023-11-23 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0004_job_resolved_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='language',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='実装言語'),
        ),
        migrations.AddField(
            model_name='score',
            name='language',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='実装言語'),
        ),
    ]
