version: '3'

services:
  portal-app:
    restart: always
    build: ./
    ports:
      - "127.0.0.1:8000:80"
    depends_on:
      - postgres
      - redis
    environment:
      - DJANGO_DATABASE_TYPE=postgres
      - GITHUB_KEY
      - GITHUB_SECRET
      - DJANGO_ALLOWED_HOST
      - DJANGO_DEBUG
      - SLACK_ENDPOINT_URL
      - CONTEST
    volumes:
      - "./log/django/:/var/log/django"
      - "staticdata:/opt/app/static/"
      - "mediadata:/opt/app/media/"
  discard_forever:
    restart: always
    build: ./
    depends_on:
      - portal-app
    environment:
      - DJANGO_DATABASE_TYPE=postgres
    command: python manage.py discard_forever
  postgres:
    restart: always
    image: postgres:12-alpine
    environment:
      - POSTGRES_DB=isucon
      - POSTGRES_USER=isucon
      - POSTGRES_PASSWORD=password
    volumes:
      - "dbdata:/var/lib/postgresql/data"
  redis:
    image: redis:5.0-alpine
    ports:
      - "127.0.0.1:6379:6379"
volumes:
  dbdata:
  staticdata:
  mediadata:
