env:
  browser: true
  es6: true
extends:
  - 'eslint:recommended'
  - 'plugin:react/recommended'
  - 'plugin:@typescript-eslint/eslint-recommended'
  - 'plugin:import/recommended'
  - 'plugin:import/errors'
  - 'plugin:import/warnings'
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module
plugins:
  - react
  - '@typescript-eslint'
  - 'react-hooks'
rules:
  import/order: # https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/order.md
    - 'warn'
    - alphabetize: { order: asc, caseInsensitive: true }
      newlines-between: never
      pathGroups:
        - { pattern: '~/**', group: 'parent' }
        - { pattern: 'react', group: 'parent', position: 'before' }
  import/no-unresolved: 0
  'no-unused-vars': 'off'
  '@typescript-eslint/no-unused-vars': ['error']
  '@typescript-eslint/explicit-module-boundary-types': ['error']
  'react/jsx-curly-brace-presence': 'error'
  'react-hooks/rules-of-hooks': 'error'
  'arrow-body-style': ['error', 'as-needed']
  'dot-notation': 'error'
settings:
  react:
    version: 'detect'
