# Generated by Django 4.2.4 on 2023-08-22 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='is_guest',
            field=models.BooleanField(blank=True, default=False, verbose_name='ゲストチーム'),
            preserve_default=False,
        ),
    ]
