# Generated by Django 4.2.4 on 2023-08-31 07:29

from django.db import migrations, models
import django.db.models.deletion
import isucon.portal.authentication.models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_team_created_at_team_declined_at_team_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterCoupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最終更新日時')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='利用日時')),
                ('name', models.CharField(max_length=200, verbose_name='送付先')),
                ('token', models.CharField(default=isucon.portal.authentication.models.default_register_coupon_token, max_length=100, unique=True, verbose_name='トークン')),
                ('team', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.team', verbose_name='チーム')),
            ],
            options={
                'verbose_name': '登録クーポン',
                'verbose_name_plural': '登録クーポン',
                'ordering': ('-created_at',),
            },
        ),
    ]
