# Generated by Django 4.2.4 on 2023-09-13 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_registercoupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='discord_access_token',
            field=models.CharField(blank=True, max_length=200, verbose_name='Discord Token'),
        ),
        migrations.AddField(
            model_name='user',
            name='discord_expired_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Discord 有効期限'),
        ),
        migrations.AddField(
            model_name='user',
            name='discord_id',
            field=models.CharField(blank=True, max_length=200, verbose_name='Discord ID'),
        ),
        migrations.AddField(
            model_name='user',
            name='discord_refresh_token',
            field=models.CharField(blank=True, max_length=200, verbose_name='Discord Token'),
        ),
        migrations.AddField(
            model_name='user',
            name='discord_username',
            field=models.CharField(blank=True, max_length=200, verbose_name='Discord Username'),
        ),
    ]
