# Generated by Django 4.2.4 on 2023-09-25 08:41

from django.db import migrations, models
import isucon.portal.authentication.models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_user_discord_access_token_user_discord_expired_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='envcheck_token',
            field=models.CharField(default=isucon.portal.authentication.models.generate_envcheck_token, max_length=100, verbose_name='envcheck向けトークン'),
        ),
    ]
