# Generated by Django 4.2.4 on 2023-09-27 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_team_envcheck_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='envchecked_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='envcheck完了時刻'),
        ),
    ]
