# Generated by Django 4.2.4 on 2023-10-14 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_team_envchecked_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='banned_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='失格日時'),
        ),
    ]
