# Generated by Django 4.2.4 on 2023-11-02 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_team_banned_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='aws_coupon',
            field=models.CharField(blank=True, max_length=50, verbose_name='AWSクーポン'),
        ),
        migrations.AddField(
            model_name='team',
            name='coupon_agreed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='クーポン同意日時'),
        ),
        migrations.AddField(
            model_name='team',
            name='sacloud_coupon',
            field=models.CharField(blank=True, max_length=50, verbose_name='さくらのクラウドクーポン'),
        ),
    ]
