# Generated by Django 4.2.4 on 2023-11-02 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_team_aws_coupon_team_coupon_agreed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='want_local_participation',
            field=models.BooleanField(blank=True, default=False, verbose_name='現地参加を希望する'),
            preserve_default=False,
        ),
    ]
