# Generated by Django 4.2.4 on 2023-11-20 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_team_want_local_participation'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='is_local_participation',
            field=models.BooleanField(blank=True, default=False, verbose_name='現地参加する'),
            preserve_default=False,
        ),
    ]
