# Generated by Django 4.2.4 on 2023-11-21 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_team_is_local_participation'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='aws_az',
            field=models.CharField(choices=[('apne1-az1', 'apne1-az1'), ('apne1-az2', 'apne1-az2'), ('apne1-az4', 'apne1-az4')], default='apne1-az2', max_length=50, verbose_name='AWS AZ'),
        ),
    ]
