# Generated by Django 4.2.7 on 2023-11-23 10:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import isucon.portal.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='タイトル')),
                ('description', models.TextField(verbose_name='本文')),
                ('status', models.CharField(choices=[('accepted', '受付済み'), ('progress', '進行中'), ('waiting', '参加者対応待ち'), ('closed', 'クローズ済み')], default='accepted', max_length=10, verbose_name='ステータス')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'チケット',
                'verbose_name_plural': 'チケット',
                'ordering': (),
            },
            bases=(isucon.portal.models.LogicalDeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='TicketComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='本文')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contact.ticket')),
            ],
            options={
                'verbose_name': 'チケットコメント',
                'verbose_name_plural': 'チケットコメント',
                'ordering': (),
            },
            bases=(isucon.portal.models.LogicalDeleteMixin, models.Model),
        ),
    ]
