# Generated by Django 4.2.7 on 2023-11-24 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='genre',
            field=models.CharField(choices=[('code', '競技用コード'), ('infra', '参加者インフラ'), ('regulation', 'レギュレーション'), ('benchmark', 'ベンチマーク'), ('env', '環境チェック'), ('other', 'その他')], default='other', max_length=10, verbose_name='ジャンル'),
        ),
    ]
