# Generated by Django 4.2.7 on 2023-11-24 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_ticket_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='visibility',
            field=models.CharField(choices=[('public', '公開'), ('summary', '要約のみ公開'), ('private', '非公開')], default='private', max_length=10, verbose_name='公開範囲'),
        ),
    ]
