# Generated by Django 4.2.7 on 2023-11-24 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_ticket_visibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='summary',
            field=models.TextField(blank=True, verbose_name='要約'),
        ),
    ]
