# Generated by Django 4.2.4 on 2023-11-24 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_ticket_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('accepted', '受付済み'), ('waiting', '参加者対応待ち'), ('closed', 'クローズ済み')], default='accepted', max_length=10, verbose_name='ステータス'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='summary',
            field=models.TextField(blank=True, verbose_name='回答要約'),
        ),
    ]
