# Generated by Django 4.2.4 on 2023-09-26 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0006_team_envcheck_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnvCheckResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('name', models.CharField(max_length=100, verbose_name='テスト名')),
                ('passed', models.BooleanField(blank=True, default=False, verbose_name='成功')),
                ('ip_address', models.CharField(max_length=100, verbose_name='IPアドレス')),
                ('message', models.TextField(blank=True, verbose_name='メッセージ')),
                ('admin_message', models.TextField(blank=True, verbose_name='管理メッセージ')),
                ('raw_data', models.TextField(blank=True, verbose_name='RAWデータ')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.team')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
